using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Prim.Roslyn
{
    /// <summary>
    /// Source generator that transforms methods marked with [Continuable]
    /// to support suspension, state capture, and resumption.
    ///
    /// Note: This is a simplified implementation that demonstrates the concept.
    /// A production implementation would need more sophisticated syntax tree
    /// transformation to handle all C# constructs.
    /// </summary>
    [Generator]
    public class ContinuationGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all methods with [Continuable] attribute
            var methodDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateMethod(s),
                    transform: static (ctx, _) => GetMethodIfContinuable(ctx))
                .Where(static m => m is not null);

            // Combine with compilation
            var compilationAndMethods = context.CompilationProvider.Combine(methodDeclarations.Collect());

            // Generate source
            context.RegisterSourceOutput(compilationAndMethods,
                static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static bool IsCandidateMethod(SyntaxNode node)
        {
            return node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0;
        }

        private static MethodDeclarationSyntax GetMethodIfContinuable(GeneratorSyntaxContext context)
        {
            var methodSyntax = (MethodDeclarationSyntax)context.Node;

            foreach (var attributeList in methodSyntax.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var name = attribute.Name.ToString();
                    if (name == "Continuable" || name == "ContinuableAttribute" ||
                        name.EndsWith(".Continuable") || name.EndsWith(".ContinuableAttribute"))
                    {
                        return methodSyntax;
                    }
                }
            }

            return null;
        }

        private static void Execute(
            Compilation compilation,
            ImmutableArray<MethodDeclarationSyntax> methods,
            SourceProductionContext context)
        {
            if (methods.IsDefaultOrEmpty)
                return;

            var methodsByType = methods
                .Where(m => m is not null)
                .GroupBy(m => GetFullTypeName(m))
                .ToList();

            foreach (var group in methodsByType)
            {
                var typeName = group.Key;
                var source = GenerateTransformedMethods(typeName, group.ToList(), compilation);
                context.AddSource($"{typeName.Replace(".", "_")}_Continuations.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string GetFullTypeName(MethodDeclarationSyntax method)
        {
            var typeDecl = method.Parent as TypeDeclarationSyntax;
            if (typeDecl == null) return "UnknownType";

            var typeName = typeDecl.Identifier.Text;
            var ns = GetNamespace(typeDecl);

            return string.IsNullOrEmpty(ns) ? typeName : $"{ns}.{typeName}";
        }

        private static string GetNamespace(SyntaxNode node)
        {
            var ns = node.Ancestors()
                .OfType<BaseNamespaceDeclarationSyntax>()
                .FirstOrDefault();

            return ns?.Name.ToString() ?? "";
        }

        private static string GenerateTransformedMethods(
            string typeName,
            System.Collections.Generic.List<MethodDeclarationSyntax> methods,
            Compilation compilation)
        {
            var sb = new StringBuilder();

            var lastDot = typeName.LastIndexOf('.');
            var ns = lastDot > 0 ? typeName.Substring(0, lastDot) : null;
            var shortTypeName = lastDot > 0 ? typeName.Substring(lastDot + 1) : typeName;

            // Collect all continuable method names for this type
            var continuableMethodNames = new System.Collections.Generic.HashSet<string>(
                methods.Select(m => m.Identifier.Text));

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("#pragma warning disable CS0162 // Unreachable code detected");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Prim.Core;");
            sb.AppendLine("using Prim.Runtime;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            var firstMethod = methods.FirstOrDefault();
            var typeDecl = firstMethod?.Parent as TypeDeclarationSyntax;
            var isPartial = typeDecl?.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)) ?? false;

            if (isPartial)
            {
                var modifiers = GetTypeModifiers(typeDecl);
                sb.AppendLine($"    {modifiers}partial class {shortTypeName}");
                sb.AppendLine("    {");

                foreach (var method in methods)
                {
                    GenerateTransformedMethod(sb, method, "        ", continuableMethodNames);
                }

                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Continuation-enabled versions of {shortTypeName} methods.");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public static class {shortTypeName}Continuations");
                sb.AppendLine("    {");

                foreach (var method in methods)
                {
                    GenerateStaticTransformedMethod(sb, method, shortTypeName, "        ", continuableMethodNames);
                }

                sb.AppendLine("    }");
            }

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string GetTypeModifiers(TypeDeclarationSyntax typeDecl)
        {
            var sb = new StringBuilder();
            foreach (var mod in typeDecl.Modifiers)
            {
                if (mod.IsKind(SyntaxKind.PartialKeyword)) continue;
                sb.Append(mod.Text);
                sb.Append(' ');
            }
            return sb.ToString();
        }

        private static void GenerateTransformedMethod(
            StringBuilder sb,
            MethodDeclarationSyntax method,
            string indent,
            System.Collections.Generic.HashSet<string> continuableMethodNames)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var parameters = method.ParameterList.ToString();
            var isVoid = returnType == "void";
            var methodToken = GenerateMethodToken(method);

            var analyzer = new YieldPointAnalyzer();
            var yieldPoints = analyzer.FindYieldPoints(method);
            var locals = GetLocalVariables(method);

            sb.AppendLine();
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Continuation-enabled version of {methodName}.");
            sb.AppendLine($"{indent}/// Supports suspension at {yieldPoints.Count} yield point(s).");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public {returnType} {methodName}_Continuable{parameters}");
            sb.AppendLine($"{indent}{{");

            GenerateStateMachineBody(sb, method, yieldPoints, locals, methodToken, indent + "    ", isVoid, returnType, continuableMethodNames);

            sb.AppendLine($"{indent}}}");
        }

        private static void GenerateStaticTransformedMethod(
            StringBuilder sb,
            MethodDeclarationSyntax method,
            string originalTypeName,
            string indent,
            System.Collections.Generic.HashSet<string> continuableMethodNames)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var isStatic = method.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword));
            var isVoid = returnType == "void";
            var methodToken = GenerateMethodToken(method);

            var analyzer = new YieldPointAnalyzer();
            var yieldPoints = analyzer.FindYieldPoints(method);
            var locals = GetLocalVariables(method);

            var paramList = method.ParameterList.Parameters.ToString();
            if (!isStatic)
            {
                paramList = string.IsNullOrWhiteSpace(paramList)
                    ? $"{originalTypeName} instance"
                    : $"{originalTypeName} instance, {paramList}";
            }

            sb.AppendLine();
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Continuation-enabled wrapper for {originalTypeName}.{methodName}.");
            sb.AppendLine($"{indent}/// Supports suspension at {yieldPoints.Count} yield point(s).");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public static {returnType} {methodName}_Continuable({paramList})");
            sb.AppendLine($"{indent}{{");

            GenerateStateMachineBody(sb, method, yieldPoints, locals, methodToken, indent + "    ", isVoid, returnType, continuableMethodNames);

            sb.AppendLine($"{indent}}}");
        }

        private static void GenerateStateMachineBody(
            StringBuilder sb,
            MethodDeclarationSyntax method,
            System.Collections.Generic.List<YieldPointInfo> yieldPoints,
            System.Collections.Generic.List<(string name, string type)> locals,
            int methodToken,
            string indent,
            bool isVoid,
            string returnType,
            System.Collections.Generic.HashSet<string> continuableMethodNames)
        {
            // Get try block information
            var analyzer = new YieldPointAnalyzer();
            var (_, tryBlocks) = analyzer.FindYieldPointsAndTryBlocks(method);

            sb.AppendLine($"{indent}var __context = ScriptContext.EnsureCurrent();");
            sb.AppendLine($"{indent}const int __methodToken = {methodToken};");
            sb.AppendLine($"{indent}int __state = 0;");

            // Track which try block we're resuming into (for try-catch-finally support)
            if (tryBlocks.Count > 0)
            {
                sb.AppendLine($"{indent}int __tryBlockState = -1; // Which try block to resume into (-1 = none)");
            }
            sb.AppendLine();

            // Declare all locals at outer scope
            foreach (var local in locals)
            {
                sb.AppendLine($"{indent}{local.type} {local.name} = default({local.type});");
            }
            sb.AppendLine();

            // Restore block - set state from frame
            sb.AppendLine($"{indent}// Restore state if resuming");
            sb.AppendLine($"{indent}if (__context.IsRestoring && __context.FrameChain?.MethodToken == __methodToken)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    var __frame = __context.FrameChain;");
            sb.AppendLine($"{indent}    __context.FrameChain = __frame.Caller;");
            sb.AppendLine($"{indent}    __state = __frame.YieldPointId + 1; // Resume after yield point");
            sb.AppendLine();

            // Restore locals from slots
            for (int i = 0; i < locals.Count; i++)
            {
                var local = locals[i];
                sb.AppendLine($"{indent}    {local.name} = FrameCapture.GetSlot<{local.type}>(__frame.Slots, {i});");
            }

            // Restore try block state if present (stored in an extra slot)
            if (tryBlocks.Count > 0 && locals.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    // Restore try block state if available");
                sb.AppendLine($"{indent}    if (__frame.Slots.Length > {locals.Count})");
                sb.AppendLine($"{indent}        __tryBlockState = FrameCapture.GetSlot<int>(__frame.Slots, {locals.Count});");
            }
            sb.AppendLine();

            sb.AppendLine($"{indent}    if (__context.FrameChain == null)");
            sb.AppendLine($"{indent}        __context.IsRestoring = false;");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // Try block with state machine
            sb.AppendLine($"{indent}try");
            sb.AppendLine($"{indent}{{");

            // For now, generate a simplified version that just calls the original method
            // A full implementation would transform the body into a state machine
            sb.AppendLine($"{indent}    // State machine implementation");
            sb.AppendLine($"{indent}    // Supports try-catch-finally blocks and nested method calls.");
            sb.AppendLine();

            // Generate simplified body with yield checks
            GenerateSimplifiedBody(sb, method, yieldPoints, tryBlocks, indent + "    ", continuableMethodNames);

            sb.AppendLine($"{indent}}}");

            // Catch block for state capture
            sb.AppendLine($"{indent}catch (SuspendException __ex)");
            sb.AppendLine($"{indent}{{");
            sb.Append($"{indent}    var __slots = FrameCapture.PackSlots(");
            if (locals.Count > 0)
            {
                sb.Append(string.Join(", ", locals.Select(l => l.name)));
                if (tryBlocks.Count > 0)
                {
                    sb.Append(", __tryBlockState");
                }
            }
            else if (tryBlocks.Count > 0)
            {
                sb.Append("__tryBlockState");
            }
            sb.AppendLine(");");
            sb.AppendLine($"{indent}    var __record = FrameCapture.CaptureFrame(__methodToken, __ex.YieldPointId, __slots, __ex.FrameChain);");
            sb.AppendLine($"{indent}    __ex.FrameChain = __record;");
            sb.AppendLine($"{indent}    throw;");
            sb.AppendLine($"{indent}}}");
        }

        private static void GenerateSimplifiedBody(
            StringBuilder sb,
            MethodDeclarationSyntax method,
            System.Collections.Generic.List<YieldPointInfo> yieldPoints,
            System.Collections.Generic.List<TryBlockInfo> tryBlocks,
            string indent,
            System.Collections.Generic.HashSet<string> continuableMethodNames)
        {
            var body = method.Body;
            if (body == null)
            {
                // Expression-bodied method
                var arrow = method.ExpressionBody;
                if (arrow != null)
                {
                    var exprText = TransformContinuableMethodCalls(arrow.Expression.ToString(), continuableMethodNames);
                    sb.AppendLine($"{indent}return {exprText};");
                }
                return;
            }

            var context = new BodyGenerationContext
            {
                YieldPointIndex = 0,
                TryBlockIndex = 0,
                TryBlocks = tryBlocks,
                YieldPoints = yieldPoints,
                ContinuableMethodNames = continuableMethodNames
            };

            GenerateStatements(sb, body.Statements, context, indent);
        }

        /// <summary>
        /// Transforms method calls to [Continuable] methods to their _Continuable versions.
        /// </summary>
        private static string TransformContinuableMethodCalls(string code, System.Collections.Generic.HashSet<string> continuableMethodNames)
        {
            if (continuableMethodNames == null || continuableMethodNames.Count == 0)
                return code;

            var result = code;
            foreach (var methodName in continuableMethodNames)
            {
                // Replace method calls like "MethodName(" with "MethodName_Continuable("
                // This is a simple text replacement - handles common cases
                result = System.Text.RegularExpressions.Regex.Replace(
                    result,
                    $@"\b{methodName}\s*\(",
                    $"{methodName}_Continuable(");
            }
            return result;
        }

        private class BodyGenerationContext
        {
            public int YieldPointIndex { get; set; }
            public int TryBlockIndex { get; set; }
            public System.Collections.Generic.List<TryBlockInfo> TryBlocks { get; set; }
            public System.Collections.Generic.List<YieldPointInfo> YieldPoints { get; set; }

            /// <summary>
            /// Set of method names in this type that are marked [Continuable].
            /// Used to transform calls to these methods to their _Continuable versions.
            /// </summary>
            public System.Collections.Generic.HashSet<string> ContinuableMethodNames { get; set; }
        }

        private static void GenerateStatements(
            StringBuilder sb,
            SyntaxList<StatementSyntax> statements,
            BodyGenerationContext context,
            string indent)
        {
            foreach (var statement in statements)
            {
                GenerateStatement(sb, statement, context, indent);
            }
        }

        private static void GenerateStatement(
            StringBuilder sb,
            StatementSyntax statement,
            BodyGenerationContext context,
            string indent)
        {
            // Check if this is a loop statement - add yield point before
            if (statement is WhileStatementSyntax ||
                statement is ForStatementSyntax ||
                statement is ForEachStatementSyntax ||
                statement is DoStatementSyntax)
            {
                // Estimate cost based on loop body size (1 per statement, minimum 1)
                var loopCost = EstimateStatementCost(statement);
                sb.AppendLine($"{indent}// Yield point {context.YieldPointIndex} (loop, cost={loopCost})");
                sb.AppendLine($"{indent}__context.HandleYieldPointWithBudget({context.YieldPointIndex}, {loopCost});");
                context.YieldPointIndex++;
            }

            // Check for nested continuable method calls (calls to other [Continuable] methods)
            var nestedCall = FindContinuableMethodCall(statement, context.ContinuableMethodNames);
            if (nestedCall != null)
            {
                GenerateNestedMethodCallStatement(sb, statement, nestedCall, context, indent);
                return;
            }

            // Handle different statement types
            switch (statement)
            {
                case TryStatementSyntax tryStatement:
                    GenerateTryStatement(sb, tryStatement, context, indent);
                    break;

                case LocalDeclarationStatementSyntax localDecl:
                    // Don't redeclare - just assign
                    foreach (var variable in localDecl.Declaration.Variables)
                    {
                        if (variable.Initializer != null)
                        {
                            var initText = TransformContinuableMethodCalls(
                                variable.Initializer.Value.ToString(),
                                context.ContinuableMethodNames);
                            sb.AppendLine($"{indent}{variable.Identifier.Text} = {initText};");
                        }
                    }
                    break;

                case BlockSyntax block:
                    sb.AppendLine($"{indent}{{");
                    GenerateStatements(sb, block.Statements, context, indent + "    ");
                    sb.AppendLine($"{indent}}}");
                    break;

                case IfStatementSyntax ifStatement:
                    GenerateIfStatement(sb, ifStatement, context, indent);
                    break;

                case WhileStatementSyntax whileStatement:
                    GenerateWhileStatement(sb, whileStatement, context, indent);
                    break;

                case ForStatementSyntax forStatement:
                    GenerateForStatement(sb, forStatement, context, indent);
                    break;

                case ForEachStatementSyntax foreachStatement:
                    GenerateForEachStatement(sb, foreachStatement, context, indent);
                    break;

                case DoStatementSyntax doStatement:
                    GenerateDoStatement(sb, doStatement, context, indent);
                    break;

                default:
                    // Output the statement with continuable method calls transformed
                    var stmtText = TransformContinuableMethodCalls(
                        statement.ToFullString().TrimEnd(),
                        context.ContinuableMethodNames);
                    sb.AppendLine($"{indent}{stmtText}");
                    break;
            }
        }

        /// <summary>
        /// Finds a continuable method call within a statement (calls to [Continuable] methods).
        /// </summary>
        private static InvocationExpressionSyntax FindContinuableMethodCall(
            StatementSyntax statement,
            System.Collections.Generic.HashSet<string> continuableMethodNames)
        {
            if (continuableMethodNames == null || continuableMethodNames.Count == 0)
                return null;

            foreach (var invocation in statement.DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                var methodName = GetSimpleMethodName(invocation);
                if (continuableMethodNames.Contains(methodName))
                {
                    return invocation;
                }
            }
            return null;
        }

        private static string GetSimpleMethodName(InvocationExpressionSyntax invocation)
        {
            return invocation.Expression switch
            {
                IdentifierNameSyntax id => id.Identifier.Text,
                MemberAccessExpressionSyntax ma => ma.Name.Identifier.Text,
                _ => ""
            };
        }

        /// <summary>
        /// Generates code for a statement containing a nested continuable method call.
        /// </summary>
        private static void GenerateNestedMethodCallStatement(
            StringBuilder sb,
            StatementSyntax statement,
            InvocationExpressionSyntax nestedCall,
            BodyGenerationContext context,
            string indent)
        {
            var yieldPointId = context.YieldPointIndex++;
            var methodName = GetSimpleMethodName(nestedCall);

            sb.AppendLine();
            sb.AppendLine($"{indent}// Yield point {yieldPointId} (nested call to {methodName})");

            // Handle different statement types with nested calls
            switch (statement)
            {
                case LocalDeclarationStatementSyntax localDecl:
                    // var result = SomeMethod();
                    // The variable is already declared at the outer scope
                    // Transform to call _Continuable version
                    foreach (var variable in localDecl.Declaration.Variables)
                    {
                        if (variable.Initializer != null)
                        {
                            var varName = variable.Identifier.Text;
                            var initText = TransformContinuableMethodCalls(
                                variable.Initializer.Value.ToString(),
                                context.ContinuableMethodNames);
                            sb.AppendLine($"{indent}// Nested call: {varName} = {methodName}_Continuable(...)");
                            sb.AppendLine($"{indent}{varName} = {initText};");
                        }
                    }
                    break;

                case ExpressionStatementSyntax exprStatement:
                    // Could be assignment or just invocation
                    var exprText = TransformContinuableMethodCalls(
                        exprStatement.ToFullString().TrimEnd(),
                        context.ContinuableMethodNames);
                    if (exprStatement.Expression is AssignmentExpressionSyntax assignment)
                    {
                        // result = SomeMethod();
                        sb.AppendLine($"{indent}// Nested call: {assignment.Left} = {methodName}_Continuable(...)");
                        sb.AppendLine($"{indent}{exprText}");
                    }
                    else
                    {
                        // Just a method call: SomeMethod();
                        sb.AppendLine($"{indent}// Nested call: {methodName}_Continuable(...)");
                        sb.AppendLine($"{indent}{exprText}");
                    }
                    break;

                case ReturnStatementSyntax returnStatement:
                    // return SomeMethod();
                    var returnText = TransformContinuableMethodCalls(
                        returnStatement.ToFullString().TrimEnd(),
                        context.ContinuableMethodNames);
                    sb.AppendLine($"{indent}// Nested call in return: {methodName}_Continuable(...)");
                    sb.AppendLine($"{indent}{returnText}");
                    break;

                default:
                    // Fallback: output the statement with transformation
                    var stmtText = TransformContinuableMethodCalls(
                        statement.ToFullString().TrimEnd(),
                        context.ContinuableMethodNames);
                    sb.AppendLine($"{indent}// Nested call (unhandled statement type): {methodName}_Continuable(...)");
                    sb.AppendLine($"{indent}{stmtText}");
                    break;
            }

            sb.AppendLine();
        }

        private static void GenerateTryStatement(
            StringBuilder sb,
            TryStatementSyntax tryStatement,
            BodyGenerationContext context,
            string indent)
        {
            var tryBlockId = context.TryBlockIndex++;
            var hasFinally = tryStatement.Finally != null;
            var hasCatch = tryStatement.Catches.Count > 0;

            sb.AppendLine();
            sb.AppendLine($"{indent}// Try block {tryBlockId} (hasFinally={hasFinally}, hasCatch={hasCatch})");

            // Track which try block we're in for state capture
            if (context.TryBlocks.Count > 0)
            {
                sb.AppendLine($"{indent}__tryBlockState = {tryBlockId};");
            }

            // Generate the try block
            sb.AppendLine($"{indent}try");
            sb.AppendLine($"{indent}{{");
            GenerateStatements(sb, tryStatement.Block.Statements, context, indent + "    ");
            sb.AppendLine($"{indent}}}");

            // Generate catch clauses
            foreach (var catchClause in tryStatement.Catches)
            {
                GenerateCatchClause(sb, catchClause, context, indent);
            }

            // Generate finally block
            if (tryStatement.Finally != null)
            {
                sb.AppendLine($"{indent}finally");
                sb.AppendLine($"{indent}{{");

                // Check if we're suspending - if so, the SuspendException has already
                // propagated through and we just need to let the finally run naturally
                sb.AppendLine($"{indent}    // Finally block executes on both normal completion and suspension");
                GenerateStatements(sb, tryStatement.Finally.Block.Statements, context, indent + "    ");
                sb.AppendLine($"{indent}}}");
            }

            // Reset try block tracking after exiting
            if (context.TryBlocks.Count > 0)
            {
                sb.AppendLine($"{indent}__tryBlockState = -1;");
            }

            sb.AppendLine();
        }

        private static void GenerateCatchClause(
            StringBuilder sb,
            CatchClauseSyntax catchClause,
            BodyGenerationContext context,
            string indent)
        {
            var declaration = catchClause.Declaration;
            if (declaration != null)
            {
                var exType = declaration.Type.ToString();
                var varName = declaration.Identifier.Text;

                // If no variable name in the declaration (e.g., catch (Exception)), create one
                if (string.IsNullOrEmpty(varName))
                {
                    varName = "__catchEx";
                }

                // Don't catch SuspendException - let it propagate
                sb.AppendLine($"{indent}catch ({exType} {varName}) when (!({varName} is SuspendException))");
            }
            else
            {
                // Bare catch clause - need a filter to avoid catching SuspendException
                sb.AppendLine($"{indent}catch (Exception __catchEx) when (!(__catchEx is SuspendException))");
            }

            sb.AppendLine($"{indent}{{");
            GenerateStatements(sb, catchClause.Block.Statements, context, indent + "    ");
            sb.AppendLine($"{indent}}}");
        }

        private static void GenerateIfStatement(
            StringBuilder sb,
            IfStatementSyntax ifStatement,
            BodyGenerationContext context,
            string indent)
        {
            sb.AppendLine($"{indent}if ({ifStatement.Condition})");
            if (ifStatement.Statement is BlockSyntax block)
            {
                sb.AppendLine($"{indent}{{");
                GenerateStatements(sb, block.Statements, context, indent + "    ");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                GenerateStatement(sb, ifStatement.Statement, context, indent + "    ");
            }

            if (ifStatement.Else != null)
            {
                sb.AppendLine($"{indent}else");
                if (ifStatement.Else.Statement is BlockSyntax elseBlock)
                {
                    sb.AppendLine($"{indent}{{");
                    GenerateStatements(sb, elseBlock.Statements, context, indent + "    ");
                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    GenerateStatement(sb, ifStatement.Else.Statement, context, indent + "    ");
                }
            }
        }

        private static void GenerateWhileStatement(
            StringBuilder sb,
            WhileStatementSyntax whileStatement,
            BodyGenerationContext context,
            string indent)
        {
            sb.AppendLine($"{indent}while ({whileStatement.Condition})");
            if (whileStatement.Statement is BlockSyntax block)
            {
                sb.AppendLine($"{indent}{{");
                GenerateStatements(sb, block.Statements, context, indent + "    ");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                GenerateStatement(sb, whileStatement.Statement, context, indent + "    ");
            }
        }

        private static void GenerateForStatement(
            StringBuilder sb,
            ForStatementSyntax forStatement,
            BodyGenerationContext context,
            string indent)
        {
            var decl = forStatement.Declaration?.ToString() ?? "";
            var initializers = string.Join(", ", forStatement.Initializers.Select(i => i.ToString()));
            var condition = forStatement.Condition?.ToString() ?? "";
            var incrementors = string.Join(", ", forStatement.Incrementors.Select(i => i.ToString()));

            var initPart = !string.IsNullOrEmpty(decl) ? decl : initializers;
            sb.AppendLine($"{indent}for ({initPart}; {condition}; {incrementors})");

            if (forStatement.Statement is BlockSyntax block)
            {
                sb.AppendLine($"{indent}{{");
                GenerateStatements(sb, block.Statements, context, indent + "    ");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                GenerateStatement(sb, forStatement.Statement, context, indent + "    ");
            }
        }

        private static void GenerateForEachStatement(
            StringBuilder sb,
            ForEachStatementSyntax foreachStatement,
            BodyGenerationContext context,
            string indent)
        {
            sb.AppendLine($"{indent}foreach ({foreachStatement.Type} {foreachStatement.Identifier} in {foreachStatement.Expression})");

            if (foreachStatement.Statement is BlockSyntax block)
            {
                sb.AppendLine($"{indent}{{");
                GenerateStatements(sb, block.Statements, context, indent + "    ");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                GenerateStatement(sb, foreachStatement.Statement, context, indent + "    ");
            }
        }

        private static void GenerateDoStatement(
            StringBuilder sb,
            DoStatementSyntax doStatement,
            BodyGenerationContext context,
            string indent)
        {
            sb.AppendLine($"{indent}do");
            if (doStatement.Statement is BlockSyntax block)
            {
                sb.AppendLine($"{indent}{{");
                GenerateStatements(sb, block.Statements, context, indent + "    ");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                GenerateStatement(sb, doStatement.Statement, context, indent + "    ");
            }
            sb.AppendLine($"{indent}while ({doStatement.Condition});");
        }

        private static System.Collections.Generic.List<(string name, string type)> GetLocalVariables(MethodDeclarationSyntax method)
        {
            var locals = new System.Collections.Generic.List<(string name, string type)>();

            if (method.Body == null) return locals;

            foreach (var statement in method.Body.Statements)
            {
                if (statement is LocalDeclarationStatementSyntax localDecl)
                {
                    var typeName = localDecl.Declaration.Type.ToString();
                    // Handle var keyword
                    if (typeName == "var")
                    {
                        typeName = "object"; // Simplified - real impl would infer type
                    }
                    foreach (var variable in localDecl.Declaration.Variables)
                    {
                        locals.Add((variable.Identifier.Text, typeName));
                    }
                }
            }

            return locals;
        }

        /// <summary>
        /// Estimates the instruction cost of a statement for budget tracking.
        /// </summary>
        private static int EstimateStatementCost(StatementSyntax statement)
        {
            // Count child nodes as a rough proxy for instruction count
            // This is approximate but provides reasonable fairness
            var nodeCount = statement.DescendantNodes().Count();

            // Minimum cost of 1, cap at reasonable maximum
            return System.Math.Max(1, System.Math.Min(nodeCount, 100));
        }

        private static int GenerateMethodToken(MethodDeclarationSyntax method)
        {
            var typeName = GetFullTypeName(method);
            var methodName = method.Identifier.Text;
            var paramTypes = method.ParameterList.Parameters
                .Select(p => p.Type?.ToString() ?? "")
                .ToArray();

            return StableHashFnv1a(typeName, methodName, paramTypes);
        }

        /// <summary>
        /// Computes a stable FNV-1a hash for method identification.
        /// This must match StableHash.GenerateMethodToken in Prim.Core.
        /// </summary>
        private static int StableHashFnv1a(string typeName, string methodName, string[] paramTypes)
        {
            unchecked
            {
                const uint fnvPrime = 16777619;
                const uint fnvOffsetBasis = 2166136261;

                int ComputeStringHash(string value)
                {
                    if (value == null) return 0;
                    uint hash = fnvOffsetBasis;
                    foreach (char c in value)
                    {
                        hash ^= c;
                        hash *= fnvPrime;
                    }
                    return (int)hash;
                }

                int Combine(params int[] hashes)
                {
                    int hash = 17;
                    foreach (var h in hashes)
                    {
                        hash = ((hash << 5) + hash) ^ h;
                    }
                    return hash;
                }

                var typeHash = ComputeStringHash(typeName);
                var methodHash = ComputeStringHash(methodName);

                if (paramTypes == null || paramTypes.Length == 0)
                {
                    return Combine(typeHash, methodHash);
                }

                var hashes = new int[paramTypes.Length + 2];
                hashes[0] = typeHash;
                hashes[1] = methodHash;
                for (int i = 0; i < paramTypes.Length; i++)
                {
                    hashes[i + 2] = ComputeStringHash(paramTypes[i]);
                }

                return Combine(hashes);
            }
        }
    }
}
